spring.application.name=JournalApp
spring.mongodb.uri=mongodb+srv://priyankraj03072003_db_user:7S36ILCIYTCYQgFM@cluster0.k6rpmod.mongodb.net/?appName=Cluster0
spring.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true